# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='filename',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
