# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0003_auto_20170625_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='texthandler.UserProfile'),
        ),
    ]
