# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0004_auto_20170625_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
